---
- hosts: all

  tasks:
    - name: Group by OS
      group_by: key=os_{{ ansible_distribution }}
      changed_when: False

- hosts: tomcat-servers
  remote_user: root
  become: yes
  become_method: sudo

  roles:
    - rhel-patchmanagement
